### PR TITLE
Events endpoint

### PR DESCRIPTION
**Pull request by harrythree**
- Handlebars partials added
- HTML base separated into partials
- Bootstrap added for responsive grids
- Basic styling layout for navbar
- Meetup API integrated to pull in events endpoint
- Event list styling with responsive design
- Tests included

### CODE REVIEW

**Comment by harrythree** [comment]
Travis is failing from the missing .env file. This file includes environment variable for Meetup API. We may need to add this environment variable into Travis.

**Comment by trendsetter37** [comment]
Is it ok if I add encrypted variables into the .travis.yml file?

**Comment by harrythree** [comment]
@trendsetter37 I've never added environment variables to Travis but it looks like from reading here...

http://docs.travis-ci.com/user/environment-variables/

That what you're proposing is the way they suggest adding environment variables.

@bwestmoreland what are you thoughts? Have you done something like this before?

Also, I was using my Meetup API key when writing this, but we'll probably need to have the NodeGreenville API key for future use. This would be the one that would need to be encrypted and added to the travis.yml file.

To test this locally we'll need to have a .env file that developers/contributors would need on their local machine which would need to have this Meetup API key as well. There's a .env-example file that is in the repo for reference.

**Comment by trendsetter37** [comment]
@harrythree I think I can get it to work.  [Here](https://travis-ci.org/NodeGreenville/nodegreenville/jobs/91437215) we can see that it is loading the variables now.

```
Setting environment variables from .travis.yml
$ export MEETUP_GROUP_NAME=NodeGreenville
```

Adding to .travis.yml will load the environment variables (except for the ones that I encrypted, e.g. MEETUP_API)  but now I need to find a way to dismiss then .env file check if it is being built by travis. I think that is what is causing it to fail even when it has loaded the variables from the .travis.yml file.

```
{ [Error: ENOENT, no such file or directory '.env'] errno: -2, code: 'ENOENT', path: '.env', syscall: 'open' }
```

So it is still checking for a non-existent .env file even after loading the variables we need from the .yml

**Comment by trendsetter37** [comment]
Ok [this](https://github.com/NodeGreenville/nodegreenville/commit/64162111cad37146318a8c4964a8a5307eed3f86) commit works as expected for the environment variables. 

Build log: https://travis-ci.org/NodeGreenville/nodegreenville/jobs/91425790

The date is just off.

**Comment by harrythree** [comment]
Yea that's what I was just looking at. The date test failed because the utc offset is different for the Travis server that is being spun up. Do we have a way to set the server timezone in the travis.yml file?

**Comment by trendsetter37** [comment]
http://stackoverflow.com/questions/23371542/how-do-i-configure-travis-ci-to-use-the-correct-time-zone-for-a-rails-app#answer-23374438

**Comment by trendsetter37** [comment]
We are using EST right?

**Comment by harrythree** [comment]
Yep should be something like

```
before_install:
- export TZ=America/New_York
```

**Pull request merged**
